package workitem

import "time"

// Status is the lifecycle state of a work item.
// Allowed transitions: active -> done (via Complete), done -> active (via Reopen).
// Deletion is a soft-delete via deleted_at — it is NOT a status value.
type Status string

const (
	StatusActive Status = "active"
	StatusDone   Status = "done"
)

// WorkItem is the core domain entity. It groups multiple threads and owns a
// shared artifact folder at .meridian/work/<slug>/.
type WorkItem struct {
	ID          string
	ProjectID   string
	UserID      string
	Name        string
	Slug        string
	Description *string
	Status      Status
	IsEphemeral bool
	// Metadata stores arbitrary key/value context (e.g. priority, owner).
	// Replaces the full object on Update — no deep-merge.
	Metadata    map[string]interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

// ThreadSummary is a workitem-local DTO for associated threads.
// It intentionally avoids importing domain/llm.Thread to prevent cross-domain
// coupling. Only fields needed for work-item surfaces are included.
type ThreadSummary struct {
	ID         string
	ProjectID  string
	UserID     string
	Title      string
	WorkItemID *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  *time.Time
}

// CreateRequest carries fields needed to create a new work item.
// Slug is generated by the service layer — callers must not supply it.
type CreateRequest struct {
	Name        string
	Description *string
	Metadata    map[string]interface{}
	IsEphemeral bool
}

// UpdateRequest carries the mutable fields for a PATCH.
// nil pointer fields are left unchanged; an explicit nil Description clears it.
type UpdateRequest struct {
	Name        *string
	Description *string
	ClearDesc   bool // true means explicitly set description to NULL
	Metadata    map[string]interface{}
}
