/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtoIndexRouteImport } from './routes/proto.index'
import { Route as ProtoSpikeLayoutRouteImport } from './routes/proto.spike-layout'
import { Route as ProtoPersistentSurfacesRouteImport } from './routes/proto.persistent-surfaces'
import { Route as AuthenticatedAuthCheckRouteImport } from './routes/_authenticated/auth-check'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as ApiAuthDevLoginRouteImport } from './routes/api/auth/dev-login'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedWorkbenchWorkbenchIdRouteImport } from './routes/_authenticated/workbench/$workbenchId'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat/$threadId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedProjectsProjectIdAgentRouteImport } from './routes/_authenticated/projects/$projectId/agent'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoIndexRoute = ProtoIndexRouteImport.update({
  id: '/proto/',
  path: '/proto/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoSpikeLayoutRoute = ProtoSpikeLayoutRouteImport.update({
  id: '/proto/spike-layout',
  path: '/proto/spike-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoPersistentSurfacesRoute = ProtoPersistentSurfacesRouteImport.update({
  id: '/proto/persistent-surfaces',
  path: '/proto/persistent-surfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthCheckRoute = AuthenticatedAuthCheckRouteImport.update({
  id: '/auth-check',
  path: '/auth-check',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthDevLoginRoute = ApiAuthDevLoginRouteImport.update({
  id: '/api/auth/dev-login',
  path: '/api/auth/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkbenchWorkbenchIdRoute =
  AuthenticatedWorkbenchWorkbenchIdRouteImport.update({
    id: '/workbench/$workbenchId',
    path: '/workbench/$workbenchId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdAgentRoute =
  AuthenticatedProjectsProjectIdAgentRouteImport.update({
    id: '/projects/$projectId/agent',
    path: '/projects/$projectId/agent',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-login': typeof DevLoginRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/auth-check': typeof AuthenticatedAuthCheckRoute
  '/proto/persistent-surfaces': typeof ProtoPersistentSurfacesRoute
  '/proto/spike-layout': typeof ProtoSpikeLayoutRoute
  '/proto/': typeof ProtoIndexRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/workbench/$workbenchId': typeof AuthenticatedWorkbenchWorkbenchIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/agent': typeof AuthenticatedProjectsProjectIdAgentRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-login': typeof DevLoginRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/auth-check': typeof AuthenticatedAuthCheckRoute
  '/proto/persistent-surfaces': typeof ProtoPersistentSurfacesRoute
  '/proto/spike-layout': typeof ProtoSpikeLayoutRoute
  '/proto': typeof ProtoIndexRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/workbench/$workbenchId': typeof AuthenticatedWorkbenchWorkbenchIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/agent': typeof AuthenticatedProjectsProjectIdAgentRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/dev-login': typeof DevLoginRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_authenticated/auth-check': typeof AuthenticatedAuthCheckRoute
  '/proto/persistent-surfaces': typeof ProtoPersistentSurfacesRoute
  '/proto/spike-layout': typeof ProtoSpikeLayoutRoute
  '/proto/': typeof ProtoIndexRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/workbench/$workbenchId': typeof AuthenticatedWorkbenchWorkbenchIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/agent': typeof AuthenticatedProjectsProjectIdAgentRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-login'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/auth-check'
    | '/proto/persistent-surfaces'
    | '/proto/spike-layout'
    | '/proto/'
    | '/chat/$threadId'
    | '/workbench/$workbenchId'
    | '/api/auth/callback'
    | '/api/auth/dev-login'
    | '/projects/'
    | '/projects/$projectId/agent'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-login'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/auth-check'
    | '/proto/persistent-surfaces'
    | '/proto/spike-layout'
    | '/proto'
    | '/chat/$threadId'
    | '/workbench/$workbenchId'
    | '/api/auth/callback'
    | '/api/auth/dev-login'
    | '/projects'
    | '/projects/$projectId/agent'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/dev-login'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/_authenticated/auth-check'
    | '/proto/persistent-surfaces'
    | '/proto/spike-layout'
    | '/proto/'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/workbench/$workbenchId'
    | '/api/auth/callback'
    | '/api/auth/dev-login'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/agent'
    | '/_authenticated/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DevLoginRoute: typeof DevLoginRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ProtoPersistentSurfacesRoute: typeof ProtoPersistentSurfacesRoute
  ProtoSpikeLayoutRoute: typeof ProtoSpikeLayoutRoute
  ProtoIndexRoute: typeof ProtoIndexRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthDevLoginRoute: typeof ApiAuthDevLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/': {
      id: '/proto/'
      path: '/proto'
      fullPath: '/proto/'
      preLoaderRoute: typeof ProtoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/spike-layout': {
      id: '/proto/spike-layout'
      path: '/proto/spike-layout'
      fullPath: '/proto/spike-layout'
      preLoaderRoute: typeof ProtoSpikeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/persistent-surfaces': {
      id: '/proto/persistent-surfaces'
      path: '/proto/persistent-surfaces'
      fullPath: '/proto/persistent-surfaces'
      preLoaderRoute: typeof ProtoPersistentSurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auth-check': {
      id: '/_authenticated/auth-check'
      path: '/auth-check'
      fullPath: '/auth-check'
      preLoaderRoute: typeof AuthenticatedAuthCheckRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/dev-login': {
      id: '/api/auth/dev-login'
      path: '/api/auth/dev-login'
      fullPath: '/api/auth/dev-login'
      preLoaderRoute: typeof ApiAuthDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workbench/$workbenchId': {
      id: '/_authenticated/workbench/$workbenchId'
      path: '/workbench/$workbenchId'
      fullPath: '/workbench/$workbenchId'
      preLoaderRoute: typeof AuthenticatedWorkbenchWorkbenchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/agent': {
      id: '/_authenticated/projects/$projectId/agent'
      path: '/projects/$projectId/agent'
      fullPath: '/projects/$projectId/agent'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuthCheckRoute: typeof AuthenticatedAuthCheckRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedWorkbenchWorkbenchIdRoute: typeof AuthenticatedWorkbenchWorkbenchIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProjectsProjectIdAgentRoute: typeof AuthenticatedProjectsProjectIdAgentRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthCheckRoute: AuthenticatedAuthCheckRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedWorkbenchWorkbenchIdRoute:
    AuthenticatedWorkbenchWorkbenchIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProjectsProjectIdAgentRoute:
    AuthenticatedProjectsProjectIdAgentRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DevLoginRoute: DevLoginRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ProtoPersistentSurfacesRoute: ProtoPersistentSurfacesRoute,
  ProtoSpikeLayoutRoute: ProtoSpikeLayoutRoute,
  ProtoIndexRoute: ProtoIndexRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthDevLoginRoute: ApiAuthDevLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
