/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ProtoIndexRouteImport } from './routes/proto.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ProtoSpikeLayoutRouteImport } from './routes/proto.spike-layout'
import { Route as ProtoPersistentSurfacesRouteImport } from './routes/proto.persistent-surfaces'
import { Route as ProtoLogoMarkRouteImport } from './routes/proto.logo-mark'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAuthCheckRouteImport } from './routes/_authenticated/auth-check'
import { Route as ApiAuthDevLoginRouteImport } from './routes/api/auth/dev-login'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new'
import { Route as AuthenticatedPProjectIdRouteImport } from './routes/_authenticated/p/$projectId'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat/$threadId'
import { Route as AuthenticatedPProjectIdSplatRouteImport } from './routes/_authenticated/p/$projectId/$'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoIndexRoute = ProtoIndexRouteImport.update({
  id: '/proto/',
  path: '/proto/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ProtoSpikeLayoutRoute = ProtoSpikeLayoutRouteImport.update({
  id: '/proto/spike-layout',
  path: '/proto/spike-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoPersistentSurfacesRoute = ProtoPersistentSurfacesRouteImport.update({
  id: '/proto/persistent-surfaces',
  path: '/proto/persistent-surfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoLogoMarkRoute = ProtoLogoMarkRouteImport.update({
  id: '/proto/logo-mark',
  path: '/proto/logo-mark',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthCheckRoute = AuthenticatedAuthCheckRouteImport.update({
  id: '/auth-check',
  path: '/auth-check',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthDevLoginRoute = ApiAuthDevLoginRouteImport.update({
  id: '/api/auth/dev-login',
  path: '/api/auth/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPProjectIdRoute = AuthenticatedPProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPProjectIdSplatRoute =
  AuthenticatedPProjectIdSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedPProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/dev-login': typeof DevLoginRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/auth-check': typeof AuthenticatedAuthCheckRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/proto/logo-mark': typeof ProtoLogoMarkRoute
  '/proto/persistent-surfaces': typeof ProtoPersistentSurfacesRoute
  '/proto/spike-layout': typeof ProtoSpikeLayoutRoute
  '/proto/': typeof ProtoIndexRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/p/$projectId': typeof AuthenticatedPProjectIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/p/$projectId/$': typeof AuthenticatedPProjectIdSplatRoute
}
export interface FileRoutesByTo {
  '/dev-login': typeof DevLoginRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/auth-check': typeof AuthenticatedAuthCheckRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/proto/logo-mark': typeof ProtoLogoMarkRoute
  '/proto/persistent-surfaces': typeof ProtoPersistentSurfacesRoute
  '/proto/spike-layout': typeof ProtoSpikeLayoutRoute
  '/': typeof AuthenticatedIndexRoute
  '/proto': typeof ProtoIndexRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/p/$projectId': typeof AuthenticatedPProjectIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/p/$projectId/$': typeof AuthenticatedPProjectIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/dev-login': typeof DevLoginRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_authenticated/auth-check': typeof AuthenticatedAuthCheckRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/proto/logo-mark': typeof ProtoLogoMarkRoute
  '/proto/persistent-surfaces': typeof ProtoPersistentSurfacesRoute
  '/proto/spike-layout': typeof ProtoSpikeLayoutRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/proto/': typeof ProtoIndexRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/p/$projectId': typeof AuthenticatedPProjectIdRouteWithChildren
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/_authenticated/p/$projectId/$': typeof AuthenticatedPProjectIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-login'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/auth-check'
    | '/billing'
    | '/proto/logo-mark'
    | '/proto/persistent-surfaces'
    | '/proto/spike-layout'
    | '/proto/'
    | '/chat/$threadId'
    | '/p/$projectId'
    | '/projects/new'
    | '/api/auth/callback'
    | '/api/auth/dev-login'
    | '/p/$projectId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dev-login'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/auth-check'
    | '/billing'
    | '/proto/logo-mark'
    | '/proto/persistent-surfaces'
    | '/proto/spike-layout'
    | '/'
    | '/proto'
    | '/chat/$threadId'
    | '/p/$projectId'
    | '/projects/new'
    | '/api/auth/callback'
    | '/api/auth/dev-login'
    | '/p/$projectId/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/dev-login'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/_authenticated/auth-check'
    | '/_authenticated/billing'
    | '/proto/logo-mark'
    | '/proto/persistent-surfaces'
    | '/proto/spike-layout'
    | '/_authenticated/'
    | '/proto/'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/p/$projectId'
    | '/_authenticated/projects/new'
    | '/api/auth/callback'
    | '/api/auth/dev-login'
    | '/_authenticated/p/$projectId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DevLoginRoute: typeof DevLoginRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ProtoLogoMarkRoute: typeof ProtoLogoMarkRoute
  ProtoPersistentSurfacesRoute: typeof ProtoPersistentSurfacesRoute
  ProtoSpikeLayoutRoute: typeof ProtoSpikeLayoutRoute
  ProtoIndexRoute: typeof ProtoIndexRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthDevLoginRoute: typeof ApiAuthDevLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/': {
      id: '/proto/'
      path: '/proto'
      fullPath: '/proto/'
      preLoaderRoute: typeof ProtoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/proto/spike-layout': {
      id: '/proto/spike-layout'
      path: '/proto/spike-layout'
      fullPath: '/proto/spike-layout'
      preLoaderRoute: typeof ProtoSpikeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/persistent-surfaces': {
      id: '/proto/persistent-surfaces'
      path: '/proto/persistent-surfaces'
      fullPath: '/proto/persistent-surfaces'
      preLoaderRoute: typeof ProtoPersistentSurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/logo-mark': {
      id: '/proto/logo-mark'
      path: '/proto/logo-mark'
      fullPath: '/proto/logo-mark'
      preLoaderRoute: typeof ProtoLogoMarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auth-check': {
      id: '/_authenticated/auth-check'
      path: '/auth-check'
      fullPath: '/auth-check'
      preLoaderRoute: typeof AuthenticatedAuthCheckRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/dev-login': {
      id: '/api/auth/dev-login'
      path: '/api/auth/dev-login'
      fullPath: '/api/auth/dev-login'
      preLoaderRoute: typeof ApiAuthDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/p/$projectId': {
      id: '/_authenticated/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof AuthenticatedPProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/p/$projectId/$': {
      id: '/_authenticated/p/$projectId/$'
      path: '/$'
      fullPath: '/p/$projectId/$'
      preLoaderRoute: typeof AuthenticatedPProjectIdSplatRouteImport
      parentRoute: typeof AuthenticatedPProjectIdRoute
    }
  }
}

interface AuthenticatedPProjectIdRouteChildren {
  AuthenticatedPProjectIdSplatRoute: typeof AuthenticatedPProjectIdSplatRoute
}

const AuthenticatedPProjectIdRouteChildren: AuthenticatedPProjectIdRouteChildren =
  {
    AuthenticatedPProjectIdSplatRoute: AuthenticatedPProjectIdSplatRoute,
  }

const AuthenticatedPProjectIdRouteWithChildren =
  AuthenticatedPProjectIdRoute._addFileChildren(
    AuthenticatedPProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuthCheckRoute: typeof AuthenticatedAuthCheckRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedPProjectIdRoute: typeof AuthenticatedPProjectIdRouteWithChildren
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthCheckRoute: AuthenticatedAuthCheckRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedPProjectIdRoute: AuthenticatedPProjectIdRouteWithChildren,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DevLoginRoute: DevLoginRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ProtoLogoMarkRoute: ProtoLogoMarkRoute,
  ProtoPersistentSurfacesRoute: ProtoPersistentSurfacesRoute,
  ProtoSpikeLayoutRoute: ProtoSpikeLayoutRoute,
  ProtoIndexRoute: ProtoIndexRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthDevLoginRoute: ApiAuthDevLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
