export type ProjectId = string;
export const asProjectId = (s: string) => s as ProjectId;
export type WorkId = string;
export const asWorkId = (s: string) => s as WorkId;
export type ContextSourceId = string;
export const asContextSourceId = (s: string) => s as ContextSourceId;
export type FolderId = string;
export const asFolderId = (s: string) => s as FolderId;
export type DocumentId = string;
export const asDocumentId = (s: string) => s as DocumentId;
export type ThreadId = string;
export const asThreadId = (s: string) => s as ThreadId;
export type TurnId = string;
export const asTurnId = (s: string) => s as TurnId;
export type TurnBlockId = string;
export const asTurnBlockId = (s: string) => s as TurnBlockId;
export type ModelResponseId = string;
export const asModelResponseId = (s: string) => s as ModelResponseId;
export type AgentDefinitionId = string;
export const asAgentDefinitionId = (s: string) => s as AgentDefinitionId;
export type SkillId = string;
export const asSkillId = (s: string) => s as SkillId;
export type UserInstalledSkillId = string;
export const asUserInstalledSkillId = (s: string) => s as UserInstalledSkillId;
export type UserSubscriptionId = string;
export const asUserSubscriptionId = (s: string) => s as UserSubscriptionId;
export type CreditLotId = string;
export const asCreditLotId = (s: string) => s as CreditLotId;
export type CreditTransactionId = string;
export const asCreditTransactionId = (s: string) => s as CreditTransactionId;
export type UserId = string;
export const asUserId = (s: string) => s as UserId;
export type DocumentRestorePointId = string;
export const asDocumentRestorePointId = (s: string) => s as DocumentRestorePointId;
export type TurnDocumentTouchId = string;
export const asTurnDocumentTouchId = (s: string) => s as TurnDocumentTouchId;
export type EventJournalId = string;
export const asEventJournalId = (s: string) => s as EventJournalId;
/** Durable identity of one document authority across its fenced generations. */
export type DocumentAuthorityId = string;
export const asDocumentAuthorityId = (s: string) => s as DocumentAuthorityId;
export type ResponseCausalCutId = string;
export const asResponseCausalCutId = (s: string) => s as ResponseCausalCutId;
export type DocumentRevision = string;
export const asDocumentRevision = (s: string) => s as DocumentRevision;
