const APP_ENV_PASSTHROUGH_KEYS = [
  "DATABASE_URL",
  "TEST_USER_ID",
  "WORKOS_API_KEY",
  "WORKOS_CLIENT_ID",
  "WORKOS_COOKIE_PASSWORD",
  "WORKOS_REDIRECT_URI",
  "WORKOS_DEV_LOGIN_EMAIL",
  "WORKOS_DEV_LOGIN_PASSWORD",
  "WORKOS_DEV_LOGIN_USER_ID",
  "WORKOS_DEV_AUTOLOGIN",
  "MERIDIAN_API_ORIGIN",
  "MODEL_PROVIDER",
  "MODEL_CALL_TIMEOUT_MS",
  "MODEL_REQUEST_DEBUG_CAPTURE",
  "OBS_VERBOSE",
  "ANTHROPIC_API_KEY",
  "OPENAI_API_KEY",
  "DEEPSEEK_API_KEY",
  "OPENROUTER_API_KEY",
] as const;

export function resolveAppEnvPassthroughKeys(env: NodeJS.ProcessEnv): string[] {
  return APP_ENV_PASSTHROUGH_KEYS.filter((key) => env[key] !== undefined);
}
