package streaming

import (
	"context"
	"fmt"
	"log/slog"
	"strings"

	domaindocsys "meridian/internal/domain/docsystem"
	domainllm "meridian/internal/domain/llm"
	skill "meridian/internal/domain/skill"
)

// baseIdentityPrompt is the foundational identity prompt for Meridian.
// Tool descriptions are appended dynamically via toolSection parameter (OCP compliance).
const baseIdentityPrompt = `You are Meridian, an AI assistant with access to the user's document repository.`

// systemPromptResolver builds the final system prompt from project, thread, and skills
// Implements domainllm.SystemPromptResolver interface
//
// Skills metadata (names/descriptions) is NOT handled here — it flows through the tool
// system via skill_invoke's enriched ToolMetadata. This ensures skills metadata is
// naturally absent when a model doesn't support tools (SRP compliance).
type systemPromptResolver struct {
	projectRepo  domaindocsys.ProjectStore
	threadRepo   domainllm.ThreadStore
	skillService skill.ProjectSkillService
	logger       *slog.Logger
}

// NewSystemPromptResolver creates a new system prompt resolver
func NewSystemPromptResolver(
	projectRepo domaindocsys.ProjectStore,
	threadRepo domainllm.ThreadStore,
	skillService skill.ProjectSkillService,
	logger *slog.Logger,
) domainllm.SystemPromptResolver {
	return &systemPromptResolver{
		projectRepo:  projectRepo,
		threadRepo:   threadRepo,
		skillService: skillService,
		logger:       logger,
	}
}

// Resolve builds the final system prompt by concatenating:
// 1. Base system prompt (always included - Meridian identity + tool section)
// 2. user-provided system prompt (from request_params.system)
// 3. project.system_prompt
// 4. thread.system_prompt
// 5. Content of each selected skill loaded from DB via skill service
//
// projectID is used on cold start (threadID == "") to load the project system prompt
// and skills metadata directly, since the thread doesn't exist yet to infer the project.
//
// toolSection is a pre-built string describing available tools and guidelines.
// This is generated by ToolRegistry.BuildSystemPromptSection() to enable OCP compliance.
// Pass an empty string if no tools are enabled.
func (r *systemPromptResolver) Resolve(
	ctx context.Context,
	threadID string,
	projectID string,
	userID string,
	userSystem *string,
	selectedSkills []string,
	toolSection string,
) (*string, error) {
	r.logger.Debug("resolving system prompt",
		"thread_id", threadID,
		"project_id", projectID,
		"user_id", userID,
		"user_system_provided", userSystem != nil,
		"selected_skills", selectedSkills,
		"tool_section_length", len(toolSection),
	)

	// Build base prompt with tool section (OCP compliance - tools self-describe)
	basePrompt := r.buildBasePrompt(toolSection)

	var parts []string
	parts = append(parts, basePrompt)

	// For cold start (new thread), threadID is empty — use projectID directly
	// to load project system prompt and skills metadata.
	if threadID == "" {
		r.logger.Debug("cold start detected (empty threadID), loading project prompt via projectID",
			"project_id", projectID,
		)

		if userSystem != nil && *userSystem != "" {
			parts = append(parts, *userSystem)
		}

		// Load project system prompt using projectID
		if projectID != "" {
			project, err := r.projectRepo.GetByID(ctx, projectID, userID)
			if err != nil {
				return nil, fmt.Errorf("load project (cold start): %w", err)
			}
			if project.SystemPrompt != nil && *project.SystemPrompt != "" {
				r.logger.Debug("project system prompt found (cold start)", "length", len(*project.SystemPrompt))
				parts = append(parts, *project.SystemPrompt)
			}
		}

		result := strings.Join(parts, "\n\n")
		return &result, nil
	}

	// 1. User-provided system prompt (highest priority after base)
	if userSystem != nil && *userSystem != "" {
		r.logger.Debug("user system prompt found", "length", len(*userSystem))
		parts = append(parts, *userSystem)
	}

	// 2. Load thread to get project ID
	thread, err := r.threadRepo.GetThread(ctx, threadID, userID)
	if err != nil {
		return nil, fmt.Errorf("load thread: %w", err)
	}

	// 3. Load project system prompt (user-configured project instructions)
	project, err := r.projectRepo.GetByID(ctx, thread.ProjectID, userID)
	if err != nil {
		return nil, fmt.Errorf("load project: %w", err)
	}
	if project.SystemPrompt != nil && *project.SystemPrompt != "" {
		r.logger.Debug("project system prompt found", "length", len(*project.SystemPrompt))
		parts = append(parts, *project.SystemPrompt)
	}

	// 4. Load thread system prompt
	if thread.SystemPrompt != nil && *thread.SystemPrompt != "" {
		r.logger.Debug("thread system prompt found", "length", len(*thread.SystemPrompt))
		parts = append(parts, *thread.SystemPrompt)
	}

	// 5. Load selected skills from DB via skill service
	if len(selectedSkills) > 0 {
		skillsContent, err := r.loadSkills(ctx, userID, thread.ProjectID, selectedSkills)
		if err != nil {
			return nil, fmt.Errorf("load skills: %w", err)
		}
		if skillsContent != "" {
			parts = append(parts, skillsContent)
		}
	}

	// Concatenate all parts (always has at least base prompt)
	result := strings.Join(parts, "\n\n")
	r.logger.Debug("system prompt resolved",
		"total_length", len(result),
		"parts_count", len(parts),
	)
	return &result, nil
}

// loadSkills loads the content for each selected skill from DB via skill service
func (r *systemPromptResolver) loadSkills(
	ctx context.Context,
	userID string,
	projectID string,
	selectedSkills []string,
) (string, error) {
	r.logger.Debug("loading skills",
		"project_id", projectID,
		"skills_count", len(selectedSkills),
		"skills", selectedSkills,
	)

	var parts []string

	// Add header explaining the skills
	if len(selectedSkills) > 0 {
		parts = append(parts, "You have access to the following skills. View additional reference materials using tree(\".meridian/skills/{skill_name}\") and view(\".meridian/skills/{skill_name}/{file}\"):")
	}

	loadedCount := 0
	for _, skillName := range selectedSkills {
		content, err := r.skillService.LoadSkillContent(ctx, userID, projectID, skillName)
		if err != nil {
			r.logger.Warn("failed to load skill",
				"skill", skillName,
				"project_id", projectID,
				"error", err,
			)
			continue
		}

		r.logger.Debug("skill loaded successfully",
			"skill", skillName,
			"content_length", len(content),
		)
		loadedCount++

		// Format skill with path and code block wrapper
		skillPath := fmt.Sprintf(".meridian/skills/%s/SKILL.md", skillName)
		skillFormatted := fmt.Sprintf("%s:\n```\n%s\n```", skillPath, content)
		parts = append(parts, skillFormatted)
	}

	r.logger.Debug("skills loading complete",
		"requested", len(selectedSkills),
		"loaded", loadedCount,
		"failed", len(selectedSkills)-loadedCount,
	)

	return strings.Join(parts, "\n\n"), nil
}

// buildBasePrompt constructs the base system prompt with the tool section.
// toolSection is pre-built by ToolRegistry.BuildSystemPromptSection() for OCP compliance.
func (r *systemPromptResolver) buildBasePrompt(toolSection string) string {
	var sb strings.Builder
	sb.WriteString(baseIdentityPrompt)

	// Append tool section if provided (OCP compliance - generated from tool metadata)
	if toolSection != "" {
		sb.WriteString(toolSection)
	}

	return sb.String()
}
