/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsSlugRouteImport } from './routes/_authenticated/projects/$slug'
import { Route as AuthenticatedProjectsSlugTreeRouteImport } from './routes/_authenticated/projects/$slug/tree'
import { Route as AuthenticatedProjectsSlugThreadsRouteImport } from './routes/_authenticated/projects/$slug/threads'
import { Route as AuthenticatedProjectsSlugSkillsSkillNameRouteImport } from './routes/_authenticated/projects/$slug/skills/$skillName'
import { Route as AuthenticatedProjectsSlugDocumentsSplatRouteImport } from './routes/_authenticated/projects/$slug/documents/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsSlugRoute =
  AuthenticatedProjectsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsSlugTreeRoute =
  AuthenticatedProjectsSlugTreeRouteImport.update({
    id: '/tree',
    path: '/tree',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugThreadsRoute =
  AuthenticatedProjectsSlugThreadsRouteImport.update({
    id: '/threads',
    path: '/threads',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugSkillsSkillNameRoute =
  AuthenticatedProjectsSlugSkillsSkillNameRouteImport.update({
    id: '/skills/$skillName',
    path: '/skills/$skillName',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugDocumentsSplatRoute =
  AuthenticatedProjectsSlugDocumentsSplatRouteImport.update({
    id: '/documents/$',
    path: '/documents/$',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/$slug': typeof AuthenticatedProjectsSlugRouteWithChildren
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$slug/threads': typeof AuthenticatedProjectsSlugThreadsRoute
  '/projects/$slug/tree': typeof AuthenticatedProjectsSlugTreeRoute
  '/projects/$slug/documents/$': typeof AuthenticatedProjectsSlugDocumentsSplatRoute
  '/projects/$slug/skills/$skillName': typeof AuthenticatedProjectsSlugSkillsSkillNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/$slug': typeof AuthenticatedProjectsSlugRouteWithChildren
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$slug/threads': typeof AuthenticatedProjectsSlugThreadsRoute
  '/projects/$slug/tree': typeof AuthenticatedProjectsSlugTreeRoute
  '/projects/$slug/documents/$': typeof AuthenticatedProjectsSlugDocumentsSplatRoute
  '/projects/$slug/skills/$skillName': typeof AuthenticatedProjectsSlugSkillsSkillNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/projects/$slug': typeof AuthenticatedProjectsSlugRouteWithChildren
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$slug/threads': typeof AuthenticatedProjectsSlugThreadsRoute
  '/_authenticated/projects/$slug/tree': typeof AuthenticatedProjectsSlugTreeRoute
  '/_authenticated/projects/$slug/documents/$': typeof AuthenticatedProjectsSlugDocumentsSplatRoute
  '/_authenticated/projects/$slug/skills/$skillName': typeof AuthenticatedProjectsSlugSkillsSkillNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/projects'
    | '/settings'
    | '/auth/callback'
    | '/projects/$slug'
    | '/projects/'
    | '/projects/$slug/threads'
    | '/projects/$slug/tree'
    | '/projects/$slug/documents/$'
    | '/projects/$slug/skills/$skillName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/settings'
    | '/auth/callback'
    | '/projects/$slug'
    | '/projects'
    | '/projects/$slug/threads'
    | '/projects/$slug/tree'
    | '/projects/$slug/documents/$'
    | '/projects/$slug/skills/$skillName'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/_authenticated/projects/$slug'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$slug/threads'
    | '/_authenticated/projects/$slug/tree'
    | '/_authenticated/projects/$slug/documents/$'
    | '/_authenticated/projects/$slug/skills/$skillName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$slug': {
      id: '/_authenticated/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof AuthenticatedProjectsSlugRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$slug/tree': {
      id: '/_authenticated/projects/$slug/tree'
      path: '/tree'
      fullPath: '/projects/$slug/tree'
      preLoaderRoute: typeof AuthenticatedProjectsSlugTreeRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/threads': {
      id: '/_authenticated/projects/$slug/threads'
      path: '/threads'
      fullPath: '/projects/$slug/threads'
      preLoaderRoute: typeof AuthenticatedProjectsSlugThreadsRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/skills/$skillName': {
      id: '/_authenticated/projects/$slug/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/projects/$slug/skills/$skillName'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSkillsSkillNameRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/documents/$': {
      id: '/_authenticated/projects/$slug/documents/$'
      path: '/documents/$'
      fullPath: '/projects/$slug/documents/$'
      preLoaderRoute: typeof AuthenticatedProjectsSlugDocumentsSplatRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
  }
}

interface AuthenticatedProjectsSlugRouteChildren {
  AuthenticatedProjectsSlugThreadsRoute: typeof AuthenticatedProjectsSlugThreadsRoute
  AuthenticatedProjectsSlugTreeRoute: typeof AuthenticatedProjectsSlugTreeRoute
  AuthenticatedProjectsSlugDocumentsSplatRoute: typeof AuthenticatedProjectsSlugDocumentsSplatRoute
  AuthenticatedProjectsSlugSkillsSkillNameRoute: typeof AuthenticatedProjectsSlugSkillsSkillNameRoute
}

const AuthenticatedProjectsSlugRouteChildren: AuthenticatedProjectsSlugRouteChildren =
  {
    AuthenticatedProjectsSlugThreadsRoute:
      AuthenticatedProjectsSlugThreadsRoute,
    AuthenticatedProjectsSlugTreeRoute: AuthenticatedProjectsSlugTreeRoute,
    AuthenticatedProjectsSlugDocumentsSplatRoute:
      AuthenticatedProjectsSlugDocumentsSplatRoute,
    AuthenticatedProjectsSlugSkillsSkillNameRoute:
      AuthenticatedProjectsSlugSkillsSkillNameRoute,
  }

const AuthenticatedProjectsSlugRouteWithChildren =
  AuthenticatedProjectsSlugRoute._addFileChildren(
    AuthenticatedProjectsSlugRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsSlugRoute: typeof AuthenticatedProjectsSlugRouteWithChildren
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsSlugRoute: AuthenticatedProjectsSlugRouteWithChildren,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
