package llm

import "context"

// SystemPromptResolver resolves system prompts from multiple sources.
// Combines user-provided prompts, project prompts, thread prompts, and skill prompts
// into a single consolidated system prompt for LLM requests.
type SystemPromptResolver interface {
	// Resolve builds the final system prompt by concatenating:
	// 1. Base identity prompt + tool section (from toolSection parameter)
	// 2. user-provided system prompt (from request_params.system)
	// 3. project.system_prompt
	// 4. thread.system_prompt
	// 5. Content of each selected skill loaded from DB via skill service
	//
	// projectID is used on cold start (threadID == "") to load the project system prompt
	// and skills metadata directly, since the thread doesn't exist yet.
	//
	// toolSection is a pre-built string describing available tools and guidelines.
	// This is generated by ToolRegistry.BuildSystemPromptSection() to enable OCP compliance:
	// tools self-describe via metadata, and the registry generates the section dynamically.
	// Pass an empty string if no tools are enabled.
	//
	// Returns nil if no prompts are found.
	Resolve(ctx context.Context, threadID string, projectID string, userID string, userSystem *string, selectedSkills []string, toolSection string) (*string, error)
}
